Repository superCodingProject/superCodingProject, pull requests merged in 2024-09, with the labels that each got.

#2 :building_construction:feature/프로젝트 초기 구조 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/study/supercoding_1/SuperCoding1Application.java
  src/test/java/study/supercoding_1/SuperCoding1ApplicationTests.java
Labels: enhancement

#4 :wrench:feature/환경설정
  src/main/java/study/supercoding_1/config/WebConfig.java
Labels: enhancement

#6 :wrench:feature 프로젝트 패키지 설정
  src/main/java/study/supercoding_1/controller/TestController.java
  src/main/java/study/supercoding_1/dto/TestDto.java
  src/main/java/study/supercoding_1/entity/TestEntity.java
  src/main/java/study/supercoding_1/exception/TestException.java
  src/main/java/study/supercoding_1/repository/TestRepository.java
  src/main/java/study/supercoding_1/service/TestService.java
Labels: enhancement

#13 :wrench:feature/스웨거 설정
  src/main/java/study/supercoding_1/config/SwaggerConfig.java
Labels: enhancement

#14 :sparkles: /컨트롤러 생성
  src/main/java/study/supercoding_1/controller/CommentController.java
Labels: enhancement

#18 :sparkles:feature/BaseTimeEntity 구현
  src/main/java/study/supercoding_1/SuperCoding1Application.java
  src/main/java/study/supercoding_1/entity/BaseTimeEntity.java
Labels: enhancement

#20 ✨feature/댓글 등록
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/dto/AddCommentDTO.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/repository/CommentRepository.java
  src/main/java/study/supercoding_1/service/CommentService.java
Labels: enhancement

#32 :sparkles: post entity 임시 생성
  src/main/java/study/supercoding_1/entity/Posts.java
  src/main/java/study/supercoding_1/repository/PostsRepository.java
Labels: enhancement

#34 :bug: SecurityConfig 경로 설정
  src/main/java/study/supercoding_1/config/SecurityConfig.java
Labels: bug

#35 🐛fix:AddComment 관련된 내용 수정
  build.gradle
  src/main/java/study/supercoding_1/dto/AddCommentDTO.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/service/CommentService.java
  src/test/java/study/supercoding_1/service/CommentServiceTest.java
Labels: wontfix

#37 ✨feature:getComment구현 완성
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/dto/GetCommentResponse.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/service/CommentService.java
  src/test/java/study/supercoding_1/service/CommentServiceTest.java
Labels: enhancement

#40 ✨feature/댓글 수정, 삭제 구현
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/dto/AddCommentRequest.java
  src/main/java/study/supercoding_1/dto/AddCommentResponse.java
  src/main/java/study/supercoding_1/dto/DeleteCommentResponse.java
  src/main/java/study/supercoding_1/dto/UpdateCommentRequest.java
  src/main/java/study/supercoding_1/dto/UpdateCommentResponse.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/service/CommentService.java
  src/test/java/study/supercoding_1/service/CommentServiceTest.java
Labels: bug, enhancement

#45 🐛 fix:댓글 생성, 수정시 오류 발생 해결
  src/main/java/study/supercoding_1/dto/AddCommentRequest.java
  src/main/java/study/supercoding_1/dto/UpdateCommentRequest.java
Labels: bug

#46 :bug: fix:getter 메소드 이름 컴파일 에러 수정
  src/main/java/study/supercoding_1/service/CommentService.java
Labels: bug

#47 🐛 fix: local , github 불일치 문제 해결
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/entity/Comment.java
Labels: bug

#48 :sparkles: post CRUD 작성
  src/main/java/study/supercoding_1/controller/PostController.java
  src/main/java/study/supercoding_1/dto/PostDto.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/entity/Post.java
  src/main/java/study/supercoding_1/entity/Posts.java
  src/main/java/study/supercoding_1/entity/User.java
  src/main/java/study/supercoding_1/repository/PostRepository.java
  src/main/java/study/supercoding_1/repository/PostsRepository.java
  src/main/java/study/supercoding_1/service/CommentService.java
  src/main/java/study/supercoding_1/service/PostService.java
Labels: enhancement

#50 ♻️ refactor:Response class 통합 및 더미 class 삭제
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/controller/TestController.java
  src/main/java/study/supercoding_1/dto/AddCommentResponse.java
  src/main/java/study/supercoding_1/dto/CommentResponse.java
  src/main/java/study/supercoding_1/dto/TestDto.java
  src/main/java/study/supercoding_1/dto/UpdateCommentResponse.java
  src/main/java/study/supercoding_1/entity/Comment.java
  src/main/java/study/supercoding_1/entity/TestEntity.java
  src/main/java/study/supercoding_1/exception/TestException.java
  src/main/java/study/supercoding_1/repository/TestRepository.java
  src/main/java/study/supercoding_1/service/CommentService.java
  src/main/java/study/supercoding_1/service/TestService.java
Labels: refactor

#54 🐛fix:테스트코드 도메인 이름 불일치, 댓글 조회 응답값 불일치 수정
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/test/java/study/supercoding_1/service/CommentServiceTest.java
Labels: bug

#55 :art: PostResponseDto 클래스 추가 및 POST CURD 응답형태 수정
  src/main/java/study/supercoding_1/controller/PostController.java
  src/main/java/study/supercoding_1/dto/PostDto.java
  src/main/java/study/supercoding_1/dto/PostResponseDto.java
  src/main/java/study/supercoding_1/entity/Post.java
  src/main/java/study/supercoding_1/service/PostService.java
Labels: documentation

#58 :art: post 요청 주소 변경 및 LocalDateTime 수정
  src/main/java/study/supercoding_1/controller/PostController.java
  src/main/java/study/supercoding_1/dto/PostDto.java
  src/main/java/study/supercoding_1/entity/Post.java
Labels: documentation

#59 ♻️ refactor:Comment 예외처리 및 검증
  build.gradle
  src/main/java/study/supercoding_1/dto/AddCommentRequest.java
  src/main/java/study/supercoding_1/dto/UpdateCommentRequest.java
  src/main/java/study/supercoding_1/exception/errorcode/CommonErrorCode.java
  src/main/java/study/supercoding_1/exception/errorcode/ErrorCode.java
  src/main/java/study/supercoding_1/exception/exception/CommentException.java
  src/main/java/study/supercoding_1/exception/exception/ResourceNotFoundException.java
  src/main/java/study/supercoding_1/exception/exception/RestApiException.java
  src/main/java/study/supercoding_1/exception/handler/GlobalExceptionHandler.java
  src/main/java/study/supercoding_1/exception/response/ErrorResponse.java
  src/main/java/study/supercoding_1/service/CommentService.java
Labels: refactor

#61 📝 docs:Comment API 문서화
  src/main/java/study/supercoding_1/controller/CommentController.java
  src/main/java/study/supercoding_1/dto/AddCommentRequest.java
  src/main/java/study/supercoding_1/dto/CommentResponse.java
  src/main/java/study/supercoding_1/dto/GetCommentResponse.java
  src/main/java/study/supercoding_1/dto/UpdateCommentRequest.java
Labels: documentation

#62 :bug:fix: 리엑트 연동 버그 수정
  src/main/java/study/supercoding_1/config/SecurityConfig.java
  src/main/java/study/supercoding_1/controller/PostController.java
  src/main/java/study/supercoding_1/entity/Post.java
  src/main/java/study/supercoding_1/repository/PostRepository.java
  src/main/java/study/supercoding_1/service/PostService.java
Labels: enhancement

#64 63 feature 좋아요 기능 완료
  src/main/java/study/supercoding_1/controller/LikeController.java
  src/main/java/study/supercoding_1/dto/LikeCountResponse.java
  src/main/java/study/supercoding_1/dto/LikeRequest.java
  src/main/java/study/supercoding_1/dto/LikeResponse.java
  src/main/java/study/supercoding_1/entity/Like.java
  src/main/java/study/supercoding_1/entity/Post.java
  src/main/java/study/supercoding_1/exception/exception/PostException.java
  src/main/java/study/supercoding_1/exception/exception/UserException.java
  src/main/java/study/supercoding_1/exception/handler/GlobalExceptionHandler.java
  src/main/java/study/supercoding_1/repository/LikeRepository.java
  src/main/java/study/supercoding_1/service/LikeService.java
  src/test/java/study/supercoding_1/service/LikeServiceTest.java
Labels: enhancement

#66 :memo: docs: readme 문서작성완료
  README.md
Labels: enhancement
